### ISSUE TITLE
Does Limago support the Alveo U280 Data Center Accelerator Card ?

### ISSUE THREAD

**Issue by guoqinglei** [hpcn-uam/Limago#1]
Hi,
    I see you have mentioned that Limago supports Alveo U200, so how about Alveo U280 ?
    Are there any differences for Limago from U200 to U280 ?
    Thanks a lot.

**Comment by mariodruiz** [comment]
Hello,
Currently, there is no example design for Alveo 280. However, the wrapper for the CMAC is given. There should no be major differences if you use the project for Alveo U200.
I recommend you to make a copy of the scripts/alveou200-fns-single-toe-iperf folder with the name alveou280-fns-single-toe-iperf. And change this `naudit:cmac:cmac_ALVEOu200` for `naudit:cmac:cmac_ALVEOu280`. After that you can edit this file `scripts/common_scripts/create_project.tcl`, insert this piece of code after line 15 
```
} elseif {[string first "alveou280" ${project_name}] == 0} {
	set fpga_part "xcu280-fsvh2892-2L-e"
	set fpga_board "xilinx.com:au280:part0:1.1" 
```
Finally, you can run `make create_prj_alveou280-fns-single-toe-iperf` in the root folder
If everything goes well, you should be able to get a project under projects/
Make sure that the reference clock of the CMAC is configured to 161.1328125 MHz
Let me know if you hit any issue. I can't check the design because I don't hava an Alveo u280 board 
However, I could include this changes in the repo, but I don't want to do it before checking that the design works.

**Comment by guoqinglei** [comment]
Thanks very much for your careful instructions. I will have a try when I'm available.

**Comment by mariodruiz** [comment]
There are differences between the two boards, and porting the design is not as easy as I described. I will try to push an example design today which at least produces a bitstream, but may not work. 
Do you have 100G NIC to test the design?

**Comment by guoqinglei** [comment]
Actually, I want to build the connection between two U280 cards with TCP protocol. Is it necessary to apply 100G NIC in this case ? I am new for this field. I appreciate if you could give me some advice.

**Comment by mariodruiz** [comment]
In that case, the NIC it is not necessary. However, debugging will be challenging. 
Having a NIC to test the basic operations is ideal, but not mandatory.

**Comment by mariodruiz** [comment]
@guoqinglei in the last commit I include an example project for Alveo U280. However, I have NOT verified it, but I was able to generate the bitstream.
The README explains how to change the FPGA part in the HLS code to be compatible with such board. After that, you can run `make create_prj_alveou280-fns-single-toe-iperf` in the root folder and the project should be created. Also, make sure that you are running Vivado 2018.3 NOT 2018.3.1, it implements combinational loops in the HLS part.
