### ISSUE TITLE
What should be do to imprement the cuckooCAM

### ISSUE THREAD

**Issue by skunkcabbage** [hpcn-uam/Limago#2]
###
The Limago project was cloned to local machine that installed Vivado 2018.3.

I did implement the project to VCU118 with according to the README.md, and Vivado returned result as below.

The directory of the cuckooCAM(Limago/submodules/cuckooCam) includes only cuckoo_cam.dcp and cuckoo_cam.xdc files.

What should be do to install the cuckooCAM to the project?

#### Checksum
```
commit 729d2d96d4291a980b33e40582699c8f7c92767b (HEAD -> master, origin/master, origin/HEAD)
Author: Mario Ruiz <mario.ruiz@uam.es>
Date:   Tue Jan 21 00:23:16 2020 +0100
```
#### Command
`make implement_prj_vcu118-fns-single-toe-iperf`

#### Result
```
ERROR: [Synth 8-439] module 'cuckoo_cam' not found [/home/shinsui/RDMA/Limago/Limago/src/wrapper/vcu118_fns_single_toe_wrapper.v:119]
ERROR: [Synth 8-6156] failed synthesizing module 'vcu118_fns_single_toe_wrapper' [/home/shinsui/RDMA/Limago/Limago/src/wrapper/vcu118_fns_single_toe_wrapper.v:3]
```

**Comment by mariodruiz** [comment]
Hello @skunkcabbage, did you check the [Cloning the repository](https://github.com/hpcn-uam/Limago#cloning-the-repository) section?

I think your issue is that you do not have `git lfs` installed. When you [install  git lfs](https://help.github.com/en/github/managing-large-files/installing-git-large-file-storage) perform the  following in Limago's root directory

```
git lfs install
git lfs pull 
```

Also check the md5 of the file, if the result is different from this, you still have an issue

```
md5sum submodules/cuckooCam/cuckoo_cam.dcp
408e62a58bd4af9a65bdfa3866d48ac3  submodules/cuckooCam/cuckoo_cam.dcp
```

When you fix that, just rerun the implementation in Vivado

**Comment by skunkcabbage** [comment]
Hello, @mariodruiz.

The problem was solved with to do install git lfs and do git pull.

Thank you.

**Comment by bournejason** [comment]
I met the same issue when implementing the project, but finding that the TRUE cuckoo_cam dcp file was not there...
Lucky to find answer here, maybe this should be a warning in the readme to let others know their cuckoo_cam.dcp may not be right if they don't have git lfs installed.

**Comment by mariodruiz** [comment]
In the README it is stated that you need git lfs installed to clone the repo https://github.com/hpcn-uam/Limago#cloning-the-repository. I may add a comment about cuckoo CAM
